import { describe, expect, it } from "vitest";

import { parseLatestCodexHandoffBrief } from "../src/notion/codex-handoff-brief-parser.js";

describe("parseLatestCodexHandoffBrief", () => {
  it("parses the latest persisted Codex Handoff Brief from Notion markdown", () => {
    const handoff = parseLatestCodexHandoffBrief(`
## Codex Handoff Brief: Old title
### Target Product Repo
SherifHaidar/personal-chief-of-staff
### Problem Summary
Old summary.
### Product Intent
Old intent.
### Implementation Scope
- Old scope
### Likely Affected Files or Modules
- old.ts
### Constraints / Do Not Change
- Old constraint
### Implementation Steps
- Old step
### Tests to Run
- Old test
### Acceptance Checklist
- Old acceptance
### Suggested Branch Name
codex/old
### Suggested PR Title
Old title
### Suggested PR Body
Old body
### Merge / Deploy Approval Warnings
- Old warning

## Codex Handoff Brief: Design Tasks DB
Generated by chief-of-staff-agent-office Implementation Desk at 2026-05-16T12:00:00.000Z.
### Target Product Repo
SherifHaidar/personal-chief-of-staff
### Problem Summary
Weekly To-do block insertion should be replaced with a Tasks DB write path.
### Product Intent
Make task capture durable and queryable.
### Implementation Scope
- Add the smallest Tasks DB write path.
- Preserve existing capture behavior.
### Likely Affected Files or Modules
- app/api/process-capture/route.ts
- lib/notion.ts
### Constraints / Do Not Change
- Do not merge or deploy automatically.
### Implementation Steps
- Inspect the current capture path.
- Implement the scoped DB write.
### Tests to Run
- npm test
- npm run build
### Acceptance Checklist
- Tasks DB receives the new task row.
### Suggested Branch Name
codex/tasks-db-v0
### Suggested PR Title
Design Tasks DB
### Suggested PR Body
## Summary
- Replace Weekly To-do insertion.

## Testing
- npm test
### Merge / Deploy Approval Warnings
- Merge requires Sherif approval.
- Deployment requires Sherif approval.
`);

    expect(handoff).toEqual({
      acceptanceChecklist: ["Tasks DB receives the new task row."],
      constraints: ["Do not merge or deploy automatically."],
      explicitApprovalWarnings: ["Merge requires Sherif approval.", "Deployment requires Sherif approval."],
      implementationScope: ["Add the smallest Tasks DB write path.", "Preserve existing capture behavior."],
      implementationSteps: ["Inspect the current capture path.", "Implement the scoped DB write."],
      likelyAffectedFiles: ["app/api/process-capture/route.ts", "lib/notion.ts"],
      problemSummary: "Weekly To-do block insertion should be replaced with a Tasks DB write path.",
      productIntent: "Make task capture durable and queryable.",
      suggestedBranchName: "codex/tasks-db-v0",
      suggestedPrBody: "## Summary\n- Replace Weekly To-do insertion.\n## Testing\n- npm test",
      suggestedPrTitle: "Design Tasks DB",
      targetProductRepo: "SherifHaidar/personal-chief-of-staff",
      testsToRun: ["npm test", "npm run build"],
    });
  });

  it("fails when no approved Codex Handoff marker exists", () => {
    expect(() => parseLatestCodexHandoffBrief("# Task notes")).toThrow(
      "No approved Codex Handoff Brief marker was found on the task page.",
    );
  });
});
