import type { ArchitectBrief } from "../domain/architect-brief.js";
import type { NotionAppendBlock } from "./notion-types.js";

const MAX_TEXT_LENGTH = 1_900;

function richText(content: string) {
  return [{ type: "text", text: { content } }];
}

function splitText(content: string): string[] {
  const value = content.trim() || "None.";
  const chunks: string[] = [];

  for (let index = 0; index < value.length; index += MAX_TEXT_LENGTH) {
    chunks.push(value.slice(index, index + MAX_TEXT_LENGTH));
  }

  return chunks;
}

function heading(level: 2 | 3, content: string): NotionAppendBlock {
  const type = `heading_${level}`;

  return {
    [type]: {
      rich_text: richText(content),
    },
    type,
  };
}

function paragraph(content: string): NotionAppendBlock[] {
  return splitText(content).map((chunk) => ({
    paragraph: {
      rich_text: richText(chunk),
    },
    type: "paragraph",
  }));
}

function bullet(content: string): NotionAppendBlock[] {
  return splitText(content).map((chunk) => ({
    bulleted_list_item: {
      rich_text: richText(chunk),
    },
    type: "bulleted_list_item",
  }));
}

function listSection(title: string, items: string[]): NotionAppendBlock[] {
  const blocks: NotionAppendBlock[] = [heading(3, title)];

  if (items.length === 0) {
    blocks.push(...paragraph("None."));
    return blocks;
  }

  for (const item of items) {
    blocks.push(...bullet(item));
  }

  return blocks;
}

export function renderArchitectBriefBlocks(brief: ArchitectBrief, generatedAt: Date): NotionAppendBlock[] {
  return [
    { type: "divider", divider: {} },
    heading(2, `Architect Brief: ${brief.briefTitle}`),
    ...paragraph(`Generated by chief-of-staff-agent-office at ${generatedAt.toISOString()}.`),
    heading(3, "Executive Summary"),
    ...paragraph(brief.executiveSummary),
    ...listSection("Recommended Architecture", brief.recommendedArchitecture),
    ...listSection("Proposed File Structure", brief.fileStructure),
    ...listSection("Dependencies", brief.dependencies),
    ...listSection("Required Configuration", brief.configuration),
    ...listSection("Implementation Plan", brief.implementationPlan),
    ...listSection("Risks and Mitigations", brief.risks),
    ...listSection("Open Questions", brief.openQuestions),
  ];
}

export function chunkBlocks(blocks: NotionAppendBlock[], size = 100): NotionAppendBlock[][] {
  const chunks: NotionAppendBlock[][] = [];

  for (let index = 0; index < blocks.length; index += size) {
    chunks.push(blocks.slice(index, index + size));
  }

  return chunks;
}
