import type { ArchitectBrief } from "../domain/architect-brief.js";
import {
  deriveArchitectureDecisionStatus,
  ownerDecisionNotesForArchitectBrief,
  type ArchitectBriefWritebackMetadata,
} from "../domain/architect-brief-writeback.js";
import type { CodexHandoffBrief } from "../domain/codex-handoff-brief.js";
import type { CodexDispatchRecordResult } from "../domain/codex-dispatch.js";
import type { GitHubDraftPrExecutionResult } from "../domain/github-draft-pr.js";
import type { ImplementationExecutionResult, ImplementationProposal } from "../domain/implementation-proposal.js";
import { IMPLEMENTATION_PENDING_NOTICE } from "../domain/implementation-proposal.js";
import type { PostMergeCloseoutResult } from "../domain/post-merge-closeout.js";
import type { ReviewDeskResult } from "../domain/review-desk.js";
import type { NotionAppendBlock } from "./notion-types.js";

const MAX_TEXT_LENGTH = 1_900;

function richText(content: string) {
  return [{ type: "text", text: { content } }];
}

function splitText(content: string): string[] {
  const value = content.trim() || "None.";
  const chunks: string[] = [];

  for (let index = 0; index < value.length; index += MAX_TEXT_LENGTH) {
    chunks.push(value.slice(index, index + MAX_TEXT_LENGTH));
  }

  return chunks;
}

function heading(level: 2 | 3, content: string): NotionAppendBlock {
  const type = `heading_${level}`;

  return {
    [type]: {
      rich_text: richText(content),
    },
    type,
  };
}

function paragraph(content: string): NotionAppendBlock[] {
  return splitText(content).map((chunk) => ({
    paragraph: {
      rich_text: richText(chunk),
    },
    type: "paragraph",
  }));
}

function bullet(content: string): NotionAppendBlock[] {
  return splitText(content).map((chunk) => ({
    bulleted_list_item: {
      rich_text: richText(chunk),
    },
    type: "bulleted_list_item",
  }));
}

function listSection(title: string, items: string[]): NotionAppendBlock[] {
  const blocks: NotionAppendBlock[] = [heading(3, title)];

  if (items.length === 0) {
    blocks.push(...paragraph("None."));
    return blocks;
  }

  for (const item of items) {
    blocks.push(...bullet(item));
  }

  return blocks;
}

export function renderArchitectBriefBlocks(
  brief: ArchitectBrief,
  generatedAt: Date,
  metadata?: ArchitectBriefWritebackMetadata,
): NotionAppendBlock[] {
  const decisionStatus =
    metadata?.decisionStatus ??
    deriveArchitectureDecisionStatus({
      brief,
      contextGaps: metadata?.contextGaps,
    });
  const revisionNumber = metadata?.revisionNumber ?? 1;
  const ownerDecisionNotes = ownerDecisionNotesForArchitectBrief({ brief, metadata });

  return [
    { type: "divider", divider: {} },
    heading(2, `Architect Brief: ${brief.briefTitle}`),
    ...paragraph(
      [
        "Latest approved Architect Brief.",
        `Approval timestamp: ${metadata?.approvalTimestamp ?? generatedAt.toISOString()}.`,
        `Revision: v${revisionNumber}.`,
        `Architecture disposition: ${decisionStatus}.`,
      ].join(" "),
    ),
    ...(metadata?.revisionOfPreviewRunId
      ? paragraph(`Revised from preview run ${metadata.revisionOfPreviewRunId}.`)
      : []),
    heading(3, "Executive Summary"),
    ...paragraph(brief.executiveSummary),
    ...listSection("Recommended Architecture", brief.recommendedArchitecture),
    ...listSection("Proposed File Structure", brief.fileStructure),
    ...listSection("Dependencies", brief.dependencies),
    ...listSection("Required Configuration", brief.configuration),
    ...listSection("Implementation Plan", brief.implementationPlan),
    ...listSection("Risks and Mitigations", brief.risks),
    ...listSection("Open Questions", brief.openQuestions),
    ...listSection("Owner Decision Notes", ownerDecisionNotes),
    ...(metadata?.contextGaps && metadata.contextGaps.length > 0
      ? listSection("Context Gaps", metadata.contextGaps)
      : []),
  ];
}

export function renderCodexHandoffBriefBlocks(brief: CodexHandoffBrief, generatedAt: Date): NotionAppendBlock[] {
  return [
    { type: "divider", divider: {} },
    heading(2, `Codex Handoff Brief: ${brief.suggestedPrTitle}`),
    ...paragraph(`Generated by chief-of-staff-agent-office Implementation Desk at ${generatedAt.toISOString()}.`),
    heading(3, "Target Product Repo"),
    ...paragraph(brief.targetProductRepo),
    heading(3, "Problem Summary"),
    ...paragraph(brief.problemSummary),
    heading(3, "Product Intent"),
    ...paragraph(brief.productIntent),
    ...listSection("Implementation Scope", brief.implementationScope),
    ...listSection("Likely Affected Files or Modules", brief.likelyAffectedFiles),
    ...listSection("Constraints / Do Not Change", brief.constraints),
    ...listSection("Implementation Steps", brief.implementationSteps),
    ...listSection("Tests to Run", brief.testsToRun),
    ...listSection("Acceptance Checklist", brief.acceptanceChecklist),
    heading(3, "Suggested Branch Name"),
    ...paragraph(brief.suggestedBranchName),
    heading(3, "Suggested PR Title"),
    ...paragraph(brief.suggestedPrTitle),
    heading(3, "Suggested PR Body"),
    ...paragraph(brief.suggestedPrBody),
    ...listSection("Merge / Deploy Approval Warnings", brief.explicitApprovalWarnings),
  ];
}

export function renderGitHubDraftPrResultBlocks(
  result: GitHubDraftPrExecutionResult,
  generatedAt: Date,
): NotionAppendBlock[] {
  return [
    { type: "divider", divider: {} },
    heading(2, `GitHub Draft PR: #${result.pullRequestNumber}`),
    ...paragraph(`Created by chief-of-staff-agent-office at ${generatedAt.toISOString()}.`),
    heading(3, "Pull Request"),
    ...paragraph(result.pullRequestUrl),
    heading(3, "Repository"),
    ...paragraph(result.repository),
    heading(3, "Branch"),
    ...paragraph(`${result.branchName} from ${result.baseBranch} @ ${result.baseCommitSha}`),
    heading(3, "Commit"),
    ...paragraph(result.commitSha),
    heading(3, "Handoff File"),
    ...paragraph(result.handoffFilePath),
    heading(3, "Approval Boundary"),
    ...paragraph("Draft only. Not merged, not deployed, and not approved for production. Sherif must review before merge or deployment."),
  ];
}

export function renderImplementationResultBlocks(
  result: ImplementationExecutionResult,
  proposal: ImplementationProposal,
  generatedAt: Date,
): NotionAppendBlock[] {
  return [
    { type: "divider", divider: {} },
    heading(2, `Implementation Work-Order Draft PR: #${result.pullRequestNumber}`),
    ...paragraph(`Created by chief-of-staff-agent-office Implementation Lane at ${generatedAt.toISOString()}.`),
    ...paragraph(IMPLEMENTATION_PENDING_NOTICE),
    heading(3, "Pull Request"),
    ...paragraph(result.pullRequestUrl),
    heading(3, "Repository"),
    ...paragraph(result.repository),
    heading(3, "Branch"),
    ...paragraph(`${result.branchName} from ${result.baseBranch} @ ${result.baseCommitSha}`),
    heading(3, "Commit"),
    ...paragraph(result.commitSha),
    heading(3, "Work Order File"),
    ...paragraph(result.workOrderPath),
    heading(3, "Next Action"),
    ...paragraph(result.nextAction),
    heading(3, "Approved Handoff Summary"),
    ...paragraph(`Problem: ${proposal.handoffSummary.problemSummary}`),
    ...paragraph(`Product intent: ${proposal.handoffSummary.productIntent}`),
    ...listSection("Implementation Scope", proposal.handoffSummary.implementationScope),
    ...listSection("Likely Affected Files or Modules", proposal.handoffSummary.likelyAffectedFiles),
    ...listSection("Constraints / Do Not Change", proposal.handoffSummary.constraints),
    ...listSection("Tests To Run", proposal.handoffSummary.testsToRun),
    ...listSection(
      "GitHub Checks Captured",
      result.checks.map((check) => `${check.name}: ${check.conclusion ?? check.status}`),
    ),
    heading(3, "Approval Boundary"),
    ...paragraph(
      "Draft only. Agent Office committed only the implementation work-order file. Product code has not been implemented by this step. Not merged, not deployed, and not approved for production.",
    ),
  ];
}

export function renderReviewDeskResultBlocks(result: ReviewDeskResult, generatedAt: Date): NotionAppendBlock[] {
  const review = result.review;
  const evidence = result.evidence;

  return [
    { type: "divider", divider: {} },
    heading(2, `Review + Iteration Desk: ${review.verdict}`),
    ...paragraph(`Generated by chief-of-staff-agent-office Review Desk at ${generatedAt.toISOString()}.`),
    ...paragraph(result.finalApprovalWarning),
    heading(3, "Pull Request"),
    ...paragraph(`${evidence.pullRequest.repository}#${evidence.pullRequest.pullRequestNumber}: ${evidence.pullRequest.url}`),
    heading(3, "Review Summary"),
    ...paragraph(review.summary),
    ...listSection(
      "Deterministic Gates",
      evidence.policyFindings.map((finding) => `${finding.severity}: ${finding.message}`),
    ),
    ...listSection("Risks", review.risks),
    ...listSection("Missing Evidence", review.missingEvidence),
    ...listSection(
      "Acceptance Checklist",
      review.acceptanceChecklist.map((item) => `${item.status}: ${item.criterion} - ${item.notes}`),
    ),
    ...listSection("Suggested Smoke Tests", review.suggestedSmokeTests),
    ...(review.verdict === "Needs Codex Fixes" && review.codexFixBrief
      ? [
          heading(3, "Draft Codex Fix Brief"),
          ...paragraph(review.codexFixBrief.summary),
          ...listSection("Fix Instructions", review.codexFixBrief.instructions),
          ...listSection("Verification", review.codexFixBrief.verification),
        ]
      : []),
    heading(3, "Evidence Captured"),
    ...paragraph(
      [
        `Changed files: ${evidence.pullRequest.changedFiles.map((file) => file.path).join(", ") || "None"}.`,
        `Checks: ${evidence.pullRequest.checks.map((check) => `${check.name}: ${check.conclusion ?? check.status}`).join(", ") || "None"}.`,
        `Deployments: ${evidence.pullRequest.deployments.length}.`,
        evidence.workOrder.prWorkOrderPath ? `Work order file: ${evidence.workOrder.prWorkOrderPath}.` : "Work order file: not found.",
      ].join(" "),
    ),
    heading(3, "Approval Boundary"),
    ...paragraph(
      "This review packet is evidence for Sherif. It does not merge, deploy, approve production, or dispatch Codex fixes automatically.",
    ),
  ];
}

export function renderPostMergeCloseoutBlocks(result: PostMergeCloseoutResult, generatedAt: Date): NotionAppendBlock[] {
  const pullRequest = result.evidence.pullRequest;
  const deployment = result.evidence.deployment;
  const propertyWrites = result.committed ? result.propertyWrites : result.plan.propertyWrites;
  const deploymentSummary =
    deployment.status === "found"
      ? deployment.deployments.map((item) => `${item.environment ?? "deployment"}: ${item.state ?? "unknown"}${item.url ? ` (${item.url})` : ""}`)
      : [deployment.message ?? "Deployment evidence not available."];

  return [
    { type: "divider", divider: {} },
    heading(2, `Post-Merge Closeout: ${pullRequest.repository}#${pullRequest.pullRequestNumber}`),
    ...paragraph(`Generated by chief-of-staff-agent-office Post-Merge Closeout at ${generatedAt.toISOString()}.`),
    heading(3, "Idempotency Marker"),
    ...paragraph(result.plan.closeoutMarker),
    heading(3, "Pull Request"),
    ...paragraph(`${pullRequest.title}: ${pullRequest.url}`),
    heading(3, "Selected Task PR Link Check"),
    ...paragraph(result.plan.taskPrLinkCheck.message),
    heading(3, "Merge Evidence"),
    ...paragraph(
      [
        `Merged at ${pullRequest.mergedAt}.`,
        `Merge SHA: ${pullRequest.mergeSha}.`,
        `Merged by: ${pullRequest.mergedBy ?? "unknown"}.`,
        `Branches: ${pullRequest.baseBranch} <- ${pullRequest.headBranch}.`,
      ].join(" "),
    ),
    ...listSection("Deployment Evidence", Array.isArray(deploymentSummary) ? deploymentSummary : [deploymentSummary]),
    ...listSection(
      "Notion Writes",
      propertyWrites.map((write) =>
        `${write.name}: ${write.status}${write.value !== undefined ? ` (${write.value})` : ""}${write.reason ? ` - ${write.reason}` : ""}`,
      ),
    ),
    heading(3, "Idempotency"),
    ...paragraph(
      result.committed
        ? result.blockAppended
          ? "Closeout block appended."
          : "Existing closeout marker found; block append skipped."
        : result.plan.markerAlreadyExists
          ? "Existing closeout marker found; commit will skip duplicate block append."
          : "No existing closeout marker found.",
    ),
    heading(3, "Approval Boundary"),
    ...paragraph(
      "Closeout records an already-merged PR. It does not merge, deploy, approve production, or dispatch Codex fixes automatically.",
    ),
  ];
}

export function renderCodexDispatchBlocks(result: CodexDispatchRecordResult, generatedAt: Date): NotionAppendBlock[] {
  const pullRequest = result.evidence.pullRequest;

  return [
    { type: "divider", divider: {} },
    heading(2, `Codex Dispatch: ${pullRequest.repository}#${pullRequest.pullRequestNumber}`),
    ...paragraph(`Packet recorded by chief-of-staff-agent-office Codex Dispatch at ${generatedAt.toISOString()}.`),
    heading(3, "Idempotency Marker"),
    ...paragraph(result.plan.dispatchMarker),
    heading(3, "Pull Request"),
    ...paragraph(`${pullRequest.title}: ${pullRequest.url}`),
    heading(3, "Work Order"),
    ...paragraph(result.evidence.workOrder.path),
    heading(3, "Record Status"),
    ...paragraph(result.plan.proposedRecordStatus),
    heading(3, "Next Action"),
    ...paragraph(result.plan.proposedNextAction),
    heading(3, "Direct Dispatch"),
    ...paragraph(result.plan.directDispatch.message),
    heading(3, "Packet"),
    ...paragraph(result.packet.markdown),
    heading(3, "Approval Boundary"),
    ...paragraph(
      "Codex Dispatch records a packet only. It does not start Codex, merge, deploy, approve production, or bypass Review + Iteration Desk.",
    ),
  ];
}

export function chunkBlocks(blocks: NotionAppendBlock[], size = 100): NotionAppendBlock[][] {
  const chunks: NotionAppendBlock[][] = [];

  for (let index = 0; index < blocks.length; index += size) {
    chunks.push(blocks.slice(index, index + size));
  }

  return chunks;
}
